<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ChuyenXeSeeder extends Seeder
{
    public function run()
    {
        DB::table('ChuyenXes')->insert([
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-12',
                'endDate' => '2025-05-13',
                'startTime' => '23:05',
                'endTime' => '06:05',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 130000,
                'carId' => 1,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-14',
                'startTime' => '21:30',
                'endTime' => '03:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 2,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-15',
                'endDate' => '2025-05-16',
                'startTime' => '19:00',
                'endTime' => '03:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 3,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-16',
                'endDate' => '2025-05-17',
                'startTime' => '22:30',
                'endTime' => '07:15',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 41,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 4,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-17',
                'endDate' => '2025-05-18',
                'startTime' => '19:05',
                'endTime' => '12:35',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 20,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 5,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Quãng Ngãi',
                'endProvince' => 'Lâm Đồng',
                'startLocation' => 'Quốc lộ 1A-Quãng Ngãi',
                'endLocation' => '296 Nguyên Tử Lực - Đà Lạt',
                'startDate' => '2025-05-18',
                'endDate' => '2025-05-19',
                'startTime' => '22:15',
                'endTime' => '02:50',
                'locationImage' => '/images/locationImages/lao-cai.jpg',
                'numSeats' => 20,
                'totalNumSeats' => 50,
                'price' => 180000,
                'carId' => 3,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Lâm Đồng',
                'endProvince' => 'Sài Gòn',
                'startLocation' => 'VP Đà Lạt',
                'endLocation' => 'VP Bình Tân',
                'startDate' => '2025-05-19',
                'endDate' => '2025-05-20',
                'startTime' => '19:20',
                'endTime' => '02:50',
                'locationImage' => '/images/locationImages/sai-gon.jpg',
                'numSeats' => 50,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 3,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Quãng Ngãi',
                'endProvince' => 'Sài Gòn',
                'startLocation' => 'Đức Phổ',
                'endLocation' => 'Bến xe An Sương',
                'startDate' => '2025-05-20',
                'endDate' => '2025-05-21',
                'startTime' => '19:00',
                'endTime' => '05:55',
                'locationImage' => '/images/locationImages/sai-gon.jpg',
                'numSeats' => 38,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 2,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Quãng Ngãi',
                'endProvince' => 'Lâm Đồng',
                'startLocation' => 'Quốc lộ 1A-Quãng Ngãi',
                'endLocation' => '296 Nguyên Tử Lực - Đà Lạt',
                'startDate' => '2025-05-21',
                'endDate' => '2025-05-22',
                'startTime' => '19:00',
                'endTime' => '06:30',
                'locationImage' => '/images/locationImages/lam-dong.jpg',
                'numSeats' => 10,
                'totalNumSeats' => 50,
                'price' => 150000,
                'carId' => 2,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Lâm Đồng',
                'endProvince' => 'Sài Gòn',
                'startLocation' => 'VP Đà Lạt',
                'endLocation' => 'VP Bình Tân',
                'startDate' => '2025-05-22',
                'endDate' => '2025-05-23',
                'startTime' => '22:30',
                'endTime' => '06:30',
                'locationImage' => '/images/locationImages/sai-gon.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 4,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Quãng Ngãi',
                'endProvince' => 'Sài Gòn',
                'startLocation' => 'Đức Phổ',
                'endLocation' => 'Bến xe An Sương',
                'startDate' => '2025-05-23',
                'endDate' => '2025-05-24',
                'startTime' => '18:00',
                'endTime' => '09:45',
                'locationImage' => '/images/locationImages/sai-gon.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 4,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Sài Gòn',
                'endProvince' => 'Cần Thơ',
                'startLocation' => 'Dọc QL1A - Sài Gòn',
                'endLocation' => 'Dọc QL1A - Cần Thơ',
                'startDate' => '2025-05-25',
                'endDate' => '2025-05-25',
                'startTime' => '19:44',
                'endTime' => '22:59',
                'locationImage' => '/images/locationImages/can-tho.jpg',
                'numSeats' => 10,
                'totalNumSeats' => 50,
                'price' => 150000,
                'carId' => 5,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Cần Thơ',
                'endProvince' => 'Cà Mau',
                'startLocation' => 'Dọc QL1A - Cần Thơ',
                'endLocation' => 'Bến xe Cà Mau',
                'startDate' => '2025-05-26',
                'endDate' => '2025-05-27',
                'startTime' => '22:59',
                'endTime' => '02:49',
                'locationImage' => '/images/locationImages/phan-thiet.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 5,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Phan Thiết',
                'endProvince' => 'Sài Gòn',
                'startLocation' => 'Bến xe Miền Tây',
                'endLocation' => 'Bến xe Cà Mau',
                'startDate' => '2025-05-27',
                'endDate' => '2025-05-28',
                'startTime' => '21:30',
                'endTime' => '05:05',
                'locationImage' => '/images/locationImages/sai-gon.jpg',
                'numSeats' => 45,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 5,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],

            //Chuyến An Xuân - Hà Nội
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-13',
                'startTime' => '06:00',
                'endTime' => '09:00',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 130000,
                'carId' => 1,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-15',
                'endDate' => '2025-05-15',
                'startTime' => '10:00',
                'endTime' => '13:00',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 1,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-17',
                'endDate' => '2025-05-17',
                'startTime' => '15:00',
                'endTime' => '18:00',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 2,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-18',
                'endDate' => '2025-05-18',
                'startTime' => '19:00',
                'endTime' => '22:00',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 3,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Nghệ An',
                'startLocation' => 'Bến xe Nước Ngầm',
                'endLocation' => 'An Xuân',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-13',
                'startTime' => '23:00',
                'endTime' => '02:00',
                'locationImage' => '/images/locationImages/nghe-an.jpg',
                'numSeats' => 30,
                'totalNumSeats' => 50,
                'price' => 130000,
                'carId' => 1,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-19',
                'endDate' => '2025-05-19',
                'startTime' => '06:00',
                'endTime' => '09:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 150000,
                'carId' => 5,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-20',
                'endDate' => '2025-05-20',
                'startTime' => '10:00',
                'endTime' => '13:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 5,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-21',
                'endDate' => '2025-05-21',
                'startTime' => '15:00',
                'endTime' => '18:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 5,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-22',
                'endDate' => '2025-05-22',
                'startTime' => '19:00',
                'endTime' => '22:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 5,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-23',
                'endDate' => '2025-05-24',
                'startTime' => '23:00',
                'endTime' => '02:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 5,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],

            //Chuyến Nghệ An - Quảng Trị
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-25',
                'endDate' => '2025-05-25',
                'startTime' => '06:00',
                'endTime' => '09:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 150000,
                'carId' => 1,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-26',
                'endDate' => '2025-05-26',
                'startTime' => '10:00',
                'endTime' => '13:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 2,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-28',
                'endDate' => '2025-05-28',
                'startTime' => '15:00',
                'endTime' => '18:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 3,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-29',
                'endDate' => '2025-05-29',
                'startTime' => '19:00',
                'endTime' => '22:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 4,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Nghệ An',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Văn Phòng Vinh',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-27',
                'endDate' => '2025-05-28',
                'startTime' => '23:00',
                'endTime' => '02:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 42,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 5,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],

            //Chuyến Hà Nội - Quảng Trị
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-26',
                'endDate' => '2025-05-26',
                'startTime' => '06:00',
                'endTime' => '09:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 150000,
                'carId' => 1,
                'cateCarId' => 1,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-13',
                'startTime' => '10:00',
                'endTime' => '13:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 220000,
                'carId' => 2,
                'cateCarId' => 2,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-13',
                'startTime' => '15:00',
                'endTime' => '18:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 3,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-13',
                'startTime' => '19:00',
                'endTime' => '22:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 300000,
                'carId' => 4,
                'cateCarId' => 3,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],
            [
                'startProvince' => 'Hà Nội',
                'endProvince' => 'Quảng Trị',
                'startLocation' => 'Bến xe nước ngầm',
                'endLocation' => 'Quảng Trị (Dọc Quốc Lộ 1A)',
                'startDate' => '2025-05-13',
                'endDate' => '2025-05-14',
                'startTime' => '23:00',
                'endTime' => '02:00',
                'locationImage' => '/images/locationImages/quang-tri.jpg',
                'numSeats' => 25,
                'totalNumSeats' => 50,
                'price' => 360000,
                'carId' => 5,
                'cateCarId' => 4,
                'createdAt' => Carbon::now(),
                'updatedAt' => Carbon::now(),
            ],

        ]);
    }
}
